#!/bin/bash
echo health---------------------------------------------------------------
curl --location --request GET 'localhost:7886/health'
echo \

echo register---------------------------------------------------------------
curl --location --request POST 'localhost:7886/authenticate/register' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "mattyboi",
    "email": "matty@gmail.com",
    "password": "5minrspp",
    "firstname": "matty",
    "lastname": "rank",
    "phone": "3815425986",
    "roles": ["admin","mod"]
    }'
echo \

echo login---------------------------------------------------------------
json=$(curl --location --request PATCH 'localhost:7886/authenticate/login' \
       --header 'Content-Type: application/json' \
       --data-raw '{
           "username": "mattyboi",
           "password": "5minrspp"
       }') \
&& token=$(echo $json | sed "s/{.*\"token\":\"\([^\"]*\).*}/\1/g") \
&& echo "token = $token"
echo \

echo findOne---------------------------------------------------------------
curl --location --request GET 'localhost:7886/users/get-one-user?username=mattyboi' \
--header 'Authorization: Bearer '"$token"''
echo \

echo findOneDelete---------------------------------------------------------------
curl -i --location --request GET 'localhost:7886/users/get-one-user-delete?username=mattyboi' \
        --header 'Authorization: Bearer '"$token"''
echo "token = $token"
echo \
